---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
  labels:
    chart: kube-prometheus
spec:
  chartGitPath: kube-prometheus
  releaseName: mon
  values:
    deployKubeScheduler: False
    deployKubeControllerManager: False
    global:
      rbacEnable: true
    kube_state_metrics:
      image:
        repository: gcr.io/google_containers/kube-state-metrics
        tag: v1.4.0
    alertmanager:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
    prometheus:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
    grafana:
      auth:
        anonymous:
          enabled: "false"
      adminPassword: "admin"
      storageSpec:
        class: gp2
        accessMode: "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
