---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  labels:
    chart: prometheus-operator
spec:
  chartGitPath: prometheus-operator
  releaseName: prometheus-operator
  values:
    rbacEnable: true
    image:
      repository: quay.io/coreos/prometheus-operator
      tag: v0.23.2
