---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: efk
  namespace: logging
  labels:
    chart: efk
spec:
  chartGitPath: efk
  releaseName: efk
  values:
    elasticsearch:
      clientReplicas: 0
      masterReplicas: 1
      dataReplicas: 1
      dataVolumeSize: 10Gi
      javaOpts: "-Xms1024m -Xmx1024m"
      storage:
        storageClass: gp2
      resources:
        requests:
          memory: 1024Mi
          cpu: 200m
        limits:
          memory: 2048Mi
          cpu: '1'
    fluent-bit:
      image:
        fluent_bit:
          repository: fluent/fluent-bit
          tag: 0.14.1
      rbac:
        create: true
      filter:
        mergeJSONLog: true
        enableParser: true
      parsers:
        regex:
          - name: flux
            regex: ts=(?<time>[^ ]*) caller=(?<caller>[^ ].*) component=(?<component>[^ ].*) (?<level>.*)="(?<log>[^ ].*)"
            timeKey: time
            timeFormat: "%Y-%m-%dT%H:%M:%S.%LZ"
        json:
          - name: json
            timeKey: time
            timeFormat: "%d/%b/%Y:%H:%M:%S %z"
          - name: docker
            timeKey: time
            timeFormat: "%Y-%m-%dT%H:%M:%S.%L"
            timeKeep: "On"
            decodeFieldAs: escaped
            decodeField: log
