---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: efk
  namespace: logging
  labels:
    chart: efk
spec:
  chartGitPath: efk
  releaseName: efk
  values:
    elasticsearch:
      storage:
        storageClass: gp2
      resources:
        requests:
          memory: 1024Mi
          cpu: 200m
        limits:
          memory: 2048Mi
          cpu: '1'
    fluent-bit:
      rbac:
        create: true
      parsers:
        regex:
          - name: flux
            regex: ts=(?<ts>[^ ]*) caller=(?<caller>[^ ].*) component=(?<component>[^ ].*) (?<level>.*)="(?<msg>[^ ].*)"
            timeKey: ts
            timeFormat: "%Y-%m-%dT%H:%M:%S.%L%z"
        json:
          - name: json
            timeKey: "@timestamp"
            timeFormat: "%Y-%m-%dT%H:%M:%S%z"
